### ISSUE TITLE
LVM Thins support

### ISSUE THREAD

**Issue by sirio81** [mpalmer/lvmsync#53]
Hi, this is more a question than a bug report.
Does lvmsync sipport lvm-thin?

Thank you.

**Comment by mpalmer** [comment]
Yes.

**Comment by sirio81** [comment]
Thank you.
There's a thing to clear maybe in the documentation.

> # Pre-sync all data across -- this will take some time, but while it's
> # happening the VM is still serving traffic.  pv is a great tool for
> # showing you how fast your data's moving, but you can leave it out of
> # the pipeline if you don't have it installed.
> dd if=/dev/vmsrv1/somevm-lvmsync bs=1M | pv -ptrb | ssh root@vmsrv2 dd of=/dev/vmsrv2/somevm bs=1M

Doing that I'm going to allocate all the logical volume space in the destination.
