### ISSUE TITLE
My lvmsync process is failing at this point just want to know what is the use of it. what if we are seeking more than the block size.

### ISSUE THREAD

**Issue by vengateshsubramaniyan** [mpalmer/lvmsync#61]
https://github.com/mpalmer/lvmsync/blob/4b3bf6e924d16ec4e187ac19889b76747eb096ae/lib/lvm/snapshot.rb#L56

**Comment by vengateshsubramaniyan** [comment]
Can someone help me to understand what's the use of this?. Do we need a exception handling at the point.

**Comment by vengateshsubramaniyan** [comment]
Have one more question, Is it possible to transfer the data over netcat or instead of ssh

**Comment by mpalmer** [comment]
If you're getting an exception at that point, that means that your metadata format is not one that lvmsync understands (see the comment on lines 32-37.  PRs welcome.
