### ISSUE TITLE
No data is sync : Transferred 0 bytes in 0.09 seconds

### ISSUE THREAD

**Issue by manurevah** [mpalmer/lvmsync#63]
Everything should be setup correctly, same version lvmsync on both sides (latest), yet, while doing `lvmsync /dev/vga/vm-lvmsync server:/dev/vga/vm` I keep getting a success output message, but no data is synced.

```
Data source: /dev/mapper/vga-vm
Transferred 0 bytes in 0.09 seconds
You transferred your changes Infx faster than a full dd!
```

**Comment by mpalmer** [comment]
Without enough information to be able to reproduce this problem, there really is no way for me to fix it.

**Comment by manurevah** [comment]
Sorry, I'm not sure what details to provide, I'll give this another go some time (I managed to use blocksync). Lets close this issue I guess.
Cheers,
